[package]
name = "const-lang"
version = "0.1.18"
edition = "2024"

[dependencies]
thiserror = "2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
strip = true
